### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=JetBrains Rider

###
POST http://localhost:5291/api/v1/Auth/RefreshToken
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6ImFhNGFmZWU0LTUzZjUtNDI5Yy1iZTBlLWE1ODhmZTM3NzZjZCIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6InVzZXJAZXhhbXBsZS5jb20iLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoic3RyaW5nIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiVXNlciIsImV4cCI6MTc3NDQwOTkzNSwiaXNzIjoiRS1jb21tZXJlbmNlIiwiYXVkIjoiRS1jb21tZXJlbmNlIn0.UdkaL3A5Ld1f7kbmHGR37WoH6rRoApJ11lEKzjtfNCQ
Content-Type: : application/json

{
    "refresh" : "RIOMKNAHQYETORF7VQ2CCJLEEK4HDWIC"
}

###
GET localhost:5291/api/Test
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6ImFhNGFmZWU0LTUzZjUtNDI5Yy1iZTBlLWE1ODhmZTM3NzZjZCIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6InVzZXJAZXhhbXBsZS5jb20iLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoic3RyaW5nIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiVXNlciIsImV4cCI6MTc3NDQwOTkzNSwiaXNzIjoiRS1jb21tZXJlbmNlIiwiYXVkIjoiRS1jb21tZXJlbmNlIn0.UdkaL3A5Ld1f7kbmHGR37WoH6rRoApJ11lEKzjtfNCQ


###
PUT http://localhost:5291/api/v1/Auth/update-password
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6ImFhNGFmZWU0LTUzZjUtNDI5Yy1iZTBlLWE1ODhmZTM3NzZjZCIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6InVzZXJAZXhhbXBsZS5jb20iLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoic3RyaW5nIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiVXNlciIsImV4cCI6MTc3NDQxMTg1MCwiaXNzIjoiRS1jb21tZXJlbmNlIiwiYXVkIjoiRS1jb21tZXJlbmNlIn0.HLmsW4qHg53Opyx_NUtKhC5CP7l8GjaWHfA4KsDWCtM

{
  "id": "aa4afee4-53f5-429c-be0e-a588fe3776cd",
  "password": "strings"
}

###
GET http://localhost:5291/api/v1/User/aa4afee4-53f5-429c-be0e-a588fe3776cd
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6ImFhNGFmZWU0LTUzZjUtNDI5Yy1iZTBlLWE1ODhmZTM3NzZjZCIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6InVzZXJAZXhhbXBsZS5jb20iLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoic3RyaW5nIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiVXNlciIsImV4cCI6MTc3NDQxMzU3MCwiaXNzIjoiRS1jb21tZXJlbmNlIiwiYXVkIjoiRS1jb21tZXJlbmNlIn0.5heq6Gsnm9ndbdO33v1p7wA-Vt5b7J0HsVsJ5R0j7wg